(function ($) {
    let resultInstructions = [
        ["0", "JMP", "0", "53"],
        ["1", "JMP", "0", "5"],
        ["2", "JMP", "0", "17"],
        ["3", "JMP", "0", "29"],
        ["4", "JMP", "0", "41"],
        ["5", "INT", "0", "4"],
        ["6", "LIT", "0", "5"],
        ["7", "STO", "0", "3"],
        ["8", "LOD", "0", "3"],
        ["9", "LOD", "1", "3"],
        ["10", "OPR", "0", "2"],
        ["11", "STO", "1", "5"],
        ["12", "LOD", "0", "3"],
        ["13", "LIT", "0", "3"],
        ["14", "OPR", "0", "2"],
        ["15", "STO", "1", "6"],
        ["16", "RET", "0", "0"],
        ["17", "INT", "0", "4"],
        ["18", "LIT", "0", "5"],
        ["19", "STO", "0", "3"],
        ["20", "LOD", "0", "3"],
        ["21", "LOD", "1", "3"],
        ["22", "OPR", "0", "3"],
        ["23", "STO", "1", "5"],
        ["24", "LOD", "0", "3"],
        ["25", "LIT", "0", "3"],
        ["26", "OPR", "0", "3"],
        ["27", "STO", "1", "6"],
        ["28", "RET", "0", "0"],
        ["29", "INT", "0", "4"],
        ["30", "LIT", "0", "5"],
        ["31", "STO", "0", "3"],
        ["32", "LOD", "0", "3"],
        ["33", "LOD", "1", "4"],
        ["34", "OPR", "0", "4"],
        ["35", "STO", "1", "5"],
        ["36", "LOD", "0", "3"],
        ["37", "LIT", "0", "3"],
        ["38", "OPR", "0", "4"],
        ["39", "STO", "1", "6"],
        ["40", "RET", "0", "0"],
        ["41", "INT", "0", "4"],
        ["42", "LIT", "0", "5"],
        ["43", "STO", "0", "3"],
        ["44", "LOD", "0", "3"],
        ["45", "LOD", "1", "4"],
        ["46", "OPR", "0", "5"],
        ["47", "STO", "1", "5"],
        ["48", "LOD", "0", "3"],
        ["49", "LIT", "0", "3"],
        ["50", "OPR", "0", "5"],
        ["51", "STO", "1", "6"],
        ["52", "RET", "0", "0"],
        ["53", "INT", "0", "7"],
        ["54", "LIT", "0", "10"],
        ["55", "STO", "0", "3"],
        ["56", "LIT", "0", "5"],
        ["57", "STO", "0", "4"],
        ["58", "CAL", "0", "1"],
        ["59", "CAL", "0", "2"],
        ["60", "CAL", "0", "3"],
        ["61", "CAL", "0", "4"],
        ["62", "RET", "0", "0"]
    ]

    let inputCode = "(* all procedures called and gave expected results *)\nconst t = 10, f = 5;\nvar a, b;\n\nprocedure plus;\n\tvar x;\n\tbegin\n\t\tx := 5;\n\t\ta := x + t; (* 15 in a *)\n\t\tb := x + 3; (* 8 in b*)\n\tend;\n\nprocedure minus;\n\tvar x;\n\tbegin\n\t\tx := 5;\n\t\ta := x - t; (* -5 in a *)\n\t\tb := x - 3; (* 2 in b *)\n\tend;\n\nprocedure mult;\n\tvar x;\n\tbegin\n\t\tx := 5;\n\t\ta := x * f; (* 25 in a *)\n\t\tb := x * 3; (* 15 in b *)\n\tend;\n\nprocedure div;\n\tvar x;\n\tbegin\n\t\tx := 5;\n\t\ta := x / f; (* 1 in a *)\n\t\tb := x / 3; (* 1 in b *)\n\tend;\n\nbegin\n\tcall plus;\n\tcall minus;\n\tcall mult;\n\tcall div;\nend.";


    window.runTestCase = function() {
        Parser.parse(true, inputCode);

        TestRunner.validateInstructions(resultInstructions);
    }
})($);